javascripts:
  base:
    - public/javascripts/lib/jquery-1.5.1.js
    - public/javascripts/lib/jquery-tools-1.2.5-tabs.js

  users_profile:
    - public/javascripts/src/users/profile.js

  users_show:
    - public/javascripts/src/users/show.js
    
  requests_show:
    - public/javascripts/src/requests/show.js

  requests_new:
    - public/javascripts/src/requests/new.js
